### ISSUE TITLE
banner doesn't load 2.0 Godot 4.2.2

### ISSUE THREAD

**Issue by feersow** [cengiz-pz/godot-android-admob-plugin#6] opened 2024-05-04 15:03 UTC
The banner does not load even in your demo project. I tried different combinations of demo keys and real admob account keys. changed age restrictions, sizes and position of banners. I checked during the day, not a single banner loaded. Android 13
![photo_2024-05-04_23-58-04](https://github.com/cengiz-pz/godot-android-admob-plugin/assets/69408770/c04fe42b-aada-4264-98d4-5b8c34a170d2)

**Comment by cengiz-pz** [comment] 2024-05-06 12:13
Duplicate of #5.

**Closed as completed** 2024-05-06 14:05 UTC
Labels: bug, duplicate
