### ISSUE TITLE
App layout changes after clicking on banner ad

### ISSUE THREAD

**Issue by syntaxerror247** [cengiz-pz/godot-android-admob-plugin#11] opened 2024-08-09 05:41 UTC
After clicking on banner ad and then going back to app and open keyboard, Keyboard doesn't open over the app rather it opens below it shrinking and pushing app above.
This completely changes the layout of my app which is ofcourse not desired.

> Steps to reproduce:
1. Load Demo Project
2. Add a line edit node
3. Turn off immersive mode during export
4. Click on banner ad in app
5. Go back to the app
6. Click on line edit to open keyword
App will we pushed above when keyword shows up
Before clicking ![Screenshot_2024-08-09-11-17-39-744_org.godotengine.admobdemo.jpg](https://github.com/user-attachments/assets/bef14809-1196-47c9-8f24-891b56370682)

After Clicking 
![Screenshot_2024-08-09-10-56-12-369_org.godotengine.admobdemo.jpg](https://github.com/user-attachments/assets/b4c39aea-82c3-422f-8478-5c1ac0b4a9ef)

**Comment by syntaxerror247** [comment] 2024-08-14 03:35
I found a workaround, if I hide the banner and then show it again issue resolves.

**Comment by cengiz-pz** [comment] 2024-08-19 09:42
Hi @syntaxerror247, I have followed the steps that you provided but could not reproduce this issue.

Two possibilities:
- The issue was fixed by Godot v4.3
- The issue occurs on your flavor of Android but not on the one installed on my test device.

Could you please check if you're able to reproduce this issue on Godot v4.3?

**Comment by syntaxerror247** [comment] 2024-08-19 10:55
Yes this issue is reproducible on v4.3

Note: it also occurs if ( banner ad is visible on screen) you move the app to background and then return back to app and try to use virtual keyboard

**Comment by syntaxerror247** [comment] 2024-08-19 13:16
@cengiz-pz I tried it on three android devices after exporting with Godot v4.3 and this issue is present in all of them.

android 11 (motorola)
android 13 (Xiaomi)
android 14 (Xiaomi)

**Comment by cengiz-pz** [comment] 2024-08-19 17:26
@syntaxerror247, I am able to reproduce this issue now (was missing the step to click on the ad).  I haven't been able to determine the root cause, but fear it may be an issue with the way Admob interacts with the Godot UI.  Will continue investigating sometime in the future.

**Comment by syntaxerror247** [comment] 2024-08-19 17:38
>I haven't been able to determine the root cause

Maybe to prevent banner ad from being hidden behind virtual keyboard (if its position is set at bottom)

**Comment by syntaxerror247** [comment] 2024-09-29 08:59
Any update on this ??

**Closed as completed** 2024-10-21 14:40 UTC
